HERE-TRILLIONAIRES/try-and-review

- .gitmodules
- .idea/.gitignore
- docker-compose.yml
- loki/loki-config.yml
- prometheus/prometheus.yml
Close #6 
- docker-compose 작성
- postgreSQL
- redis
- kafka
- monitoring
- loki, prometheus .yml파일 추가
- SQL 초기 스크립트 작성 -> commit (X)
- SQL 서비스 별 scheme 생성
- scheme별 계정 및 접근 권한 설정
- ID: 서비스 명 / PW: 서비스 명
- auth / auth
- recruitment / recruitment
- product / product
- review / review
- notification / notification
- statistics / statistics
- .env 파일 생성 -> commit (X)
* git submodule 추가
```
git submodule add https://github.com/HERE-TRILLIONAIRES/try-and-review-private.git ./environment
```
* docker-compose 실행 명령
```
docker-compose --env-file environment/.env up -d
```
* git submodule repo 업데이트가 있을때
```
git submodule update --remote
```
> [Feat/docker-compose] Docker-compose 작성

- com.trillionares.tryit.product/build.gradle
- com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/ProductApplication.java
- com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/domain/common/base/BaseEntity.java
- com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/domain/model/product/Product.java
- com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/domain/repository/ProductRepository.java
- com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/domain/service/ProductService.java
- com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/infrastructure/config/JpaConfig.java
- com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/presentation/controller/ProductController.java
- com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/presentation/dto/BaseResponseDto.java
- com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/presentation/dto/ProductIdResponseDto.java
- com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/presentation/dto/ProductInfoRequestDto.java
- com.trillionares.tryit.product/src/main/resources/application.yml
Close #10 
- 상품 등록 API 개발
상품 저장이 안되는 문제가 있었음. 안되는 줄 알았으나 product scheme를 확인해야하는데 public scheme를 확인하고 있었음.
상품 조회 API
> [Feat/product] 상품 등록 API 개발

- com.trillionares.tryit.product/build.gradle
- com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/ProductApplication.java
- com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/domain/common/base/BaseEntity.java
- com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/domain/model/product/Product.java
- com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/domain/repository/ProductRepository.java
- com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/domain/repository/ProductRepositoryCustom.java
- com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/domain/service/ProductService.java
- com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/infrastructure/config/JpaConfig.java
- com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/infrastructure/config/QueryDslConfig.java
- com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/presentation/controller/ProductController.java
- com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/presentation/dto/BaseResponseDto.java
- com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/presentation/dto/ProductIdResponseDto.java
- com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/presentation/dto/ProductInfoRequestDto.java
- com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/presentation/dto/ProductInfoResponseDto.java
- com.trillionares.tryit.product/src/main/resources/application.yml
- com.trillionares.tryit.product/src/test/java/com/trillionares/tryit/product/ProductApplicationTests.java
- com.trillionares.tryit.product/src/test/java/com/trillionares/tryit/product/domain/service/ProductServiceTest.java
- com.trillionares.tryit.product/src/test/resources/application-test.yml
Close #11
- 상품 등록 API 개발
- QueryDSL 적용
상품 수정 API
> [Feat/product-read] 상품 조회 API 개발

- com.trillionares.tryit.review/build.gradle
- com.trillionares.tryit.review/src/main/java/com/trillionares/tryit/review/ReviewApplication.java
- com.trillionares.tryit.review/src/main/java/com/trillionares/tryit/review/domain/common/base/BaseEntity.java
- com.trillionares.tryit.review/src/main/java/com/trillionares/tryit/review/domain/model/Review.java
- com.trillionares.tryit.review/src/main/resources/application.yml
Close #8 
- BaseEntity 생성
- 리뷰 엔티티 생성
- DB 연결 및 확인
- 공통 응답
- 없음
- BaseEntity createdBy, updatedBy, deletedBy nullable false 처리
- BaseEntity createdBy, updatedBy, deletedBy 테스트
> [Feat/review-setting] 리뷰 기본 클래스 생성 

- com.trillionares.tryit.statistics/build.gradle
- com.trillionares.tryit.statistics/src/main/java/com/trillionares/tryit/statistics/StatisticsApplication.java
- com.trillionares.tryit.statistics/src/main/java/com/trillionares/tryit/statistics/domain/common/base/BaseEntity.java
- com.trillionares.tryit.statistics/src/main/java/com/trillionares/tryit/statistics/domain/model/Statistics.java
- com.trillionares.tryit.statistics/src/main/resources/application.yml
Close #29
- BaseEntity 생성
- 통계 엔티티 생성
- DB 연결 및 확인
- 없음
- BaseEntity createdBy, updatedBy, deletedBy nullable false 처리
- BaseEntity createdBy, updatedBy, deletedBy 테스트
> [Feat/statistics-setting] 통계 기본 클래스 생성

- com.trillionares.tryit.review/build.gradle
- com.trillionares.tryit.review/src/main/java/com/trillionares/tryit/review/ReviewApplication.java
- com.trillionares.tryit.review/src/main/java/com/trillionares/tryit/review/application/dto/request/ReviewCreateRequestDto.java
- com.trillionares.tryit.review/src/main/java/com/trillionares/tryit/review/application/dto/response/ReviewCreateResponseDto.java
- com.trillionares.tryit.review/src/main/java/com/trillionares/tryit/review/application/service/ReviewService.java
- com.trillionares.tryit.review/src/main/java/com/trillionares/tryit/review/domain/common/base/BaseEntity.java
- com.trillionares.tryit.review/src/main/java/com/trillionares/tryit/review/domain/model/Review.java
- com.trillionares.tryit.review/src/main/java/com/trillionares/tryit/review/domain/repository/ReviewRepository.java
- com.trillionares.tryit.review/src/main/java/com/trillionares/tryit/review/infrastructure/persistence/ReviewRepositoryImpl.java
- com.trillionares.tryit.review/src/main/java/com/trillionares/tryit/review/presentation/controller/ReviewController.java
- com.trillionares.tryit.review/src/main/java/com/trillionares/tryit/review/presentation/dto/BaseResponse.java
- com.trillionares.tryit.review/src/main/java/com/trillionares/tryit/review/presentation/dto/ReviewCreateRequest.java
- com.trillionares.tryit.review/src/main/resources/application.yml
Close #32 
- Request, Response Dto 생성
- 리뷰 생성 API 구현
- 리뷰 생성 API 수동 테스트
- 문제 : 응답하는 과정에서 응답 타입이 올바르지 않아 에러 발생
- 해결 : 공통 응답에 Getter가 없어 올바른 응답 타입을 만들어주도록 수행
- 리뷰 이미지 처리
- 요청에 대한 값 검증 수행
- 테스트 코드 작성
> [Feat/review-create] 리뷰 생성 API 개발

- com.trillionares.tryit.product/build.gradle
- com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/ProductApplication.java
- com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/domain/common/base/BaseEntity.java
- com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/domain/model/product/Product.java
- com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/domain/repository/ProductRepository.java
- com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/domain/repository/ProductRepositoryCustom.java
- com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/domain/service/ProductService.java
- com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/infrastructure/config/JpaConfig.java
- com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/infrastructure/config/QueryDslConfig.java
- com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/presentation/controller/ProductController.java
- com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/presentation/dto/BaseResponseDto.java
- com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/presentation/dto/ProductIdResponseDto.java
- com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/presentation/dto/ProductInfoRequestDto.java
- com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/presentation/dto/ProductInfoResponseDto.java
- com.trillionares.tryit.product/src/main/resources/application.yml
- com.trillionares.tryit.product/src/test/java/com/trillionares/tryit/product/ProductApplicationTests.java
- com.trillionares.tryit.product/src/test/java/com/trillionares/tryit/product/domain/service/ProductServiceTest.java
- com.trillionares.tryit.product/src/test/resources/application-test.yml
Close #13 
- 상품 수정 API 개발
상품 삭제 API
> [Feat/product-update] 상품 수정 API 개발

- com.trillionares.tryit.review/build.gradle
- com.trillionares.tryit.review/src/main/java/com/trillionares/tryit/review/ReviewApplication.java
- com.trillionares.tryit.review/src/main/java/com/trillionares/tryit/review/application/dto/request/ReviewCreateRequestDto.java
- com.trillionares.tryit.review/src/main/java/com/trillionares/tryit/review/application/dto/response/ReviewCreateResponseDto.java
- com.trillionares.tryit.review/src/main/java/com/trillionares/tryit/review/application/dto/response/ReviewGetResponseDto.java
- com.trillionares.tryit.review/src/main/java/com/trillionares/tryit/review/application/service/ReviewService.java
- com.trillionares.tryit.review/src/main/java/com/trillionares/tryit/review/domain/common/base/BaseEntity.java
- com.trillionares.tryit.review/src/main/java/com/trillionares/tryit/review/domain/model/Review.java
- com.trillionares.tryit.review/src/main/java/com/trillionares/tryit/review/domain/repository/ReviewRepository.java
- com.trillionares.tryit.review/src/main/java/com/trillionares/tryit/review/infrastructure/persistence/ReviewRepositoryImpl.java
- com.trillionares.tryit.review/src/main/java/com/trillionares/tryit/review/presentation/controller/ReviewController.java
- com.trillionares.tryit.review/src/main/java/com/trillionares/tryit/review/presentation/dto/BaseResponse.java
- com.trillionares.tryit.review/src/main/java/com/trillionares/tryit/review/presentation/dto/ReviewCreateRequest.java
- com.trillionares.tryit.review/src/main/resources/application.yml
Close #36 
- Response Dto 생성
- 리뷰 단건 API 구현
- 리뷰 단건 API 수동 테스트
- 없음
- 리뷰 이미지 처리
- Optional 예외 처리
- 테스트 코드 작성
> [Feat/review-read] 리뷰 단건 조회 API 개발

- com.trillionares.tryit.review/build.gradle
- com.trillionares.tryit.review/src/main/java/com/trillionares/tryit/review/ReviewApplication.java
- com.trillionares.tryit.review/src/main/java/com/trillionares/tryit/review/application/dto/request/ReviewCreateRequestDto.java
- com.trillionares.tryit.review/src/main/java/com/trillionares/tryit/review/application/dto/request/ReviewUpdateRequestDto.java
- com.trillionares.tryit.review/src/main/java/com/trillionares/tryit/review/application/dto/response/ReviewCreateResponseDto.java
- com.trillionares.tryit.review/src/main/java/com/trillionares/tryit/review/application/dto/response/ReviewGetResponseDto.java
- com.trillionares.tryit.review/src/main/java/com/trillionares/tryit/review/application/dto/response/ReviewUpdateResponseDto.java
- com.trillionares.tryit.review/src/main/java/com/trillionares/tryit/review/application/service/ReviewService.java
- com.trillionares.tryit.review/src/main/java/com/trillionares/tryit/review/domain/common/base/BaseEntity.java
- com.trillionares.tryit.review/src/main/java/com/trillionares/tryit/review/domain/model/Review.java
- com.trillionares.tryit.review/src/main/java/com/trillionares/tryit/review/domain/repository/ReviewRepository.java
- com.trillionares.tryit.review/src/main/java/com/trillionares/tryit/review/infrastructure/persistence/ReviewRepositoryImpl.java
- com.trillionares.tryit.review/src/main/java/com/trillionares/tryit/review/presentation/controller/ReviewController.java
- com.trillionares.tryit.review/src/main/java/com/trillionares/tryit/review/presentation/dto/BaseResponse.java
- com.trillionares.tryit.review/src/main/java/com/trillionares/tryit/review/presentation/dto/ReviewCreateRequest.java
- com.trillionares.tryit.review/src/main/java/com/trillionares/tryit/review/presentation/dto/ReviewUpdateRequest.java
- com.trillionares.tryit.review/src/main/resources/application.yml
Close #38 
- Request, Response Dto 생성
- 리뷰 수정 API 구현
- 리뷰 수정 API 수동 테스트
- 없음
- 리뷰 이미지 처리
- Optional 예외 처리
- 요청에 대한 값 검증 수행
- 테스트 코드 작성
> [Feat/review-update] 리뷰 수정 API 개발

- com.trillionares.tryit.product/build.gradle
- com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/ProductApplication.java
- com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/domain/common/base/BaseEntity.java
- com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/domain/model/product/Product.java
- com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/domain/repository/ProductRepository.java
- com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/domain/repository/ProductRepositoryCustom.java
- com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/domain/service/ProductService.java
- com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/infrastructure/config/JpaConfig.java
- com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/infrastructure/config/QueryDslConfig.java
- com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/presentation/controller/ProductController.java
- com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/presentation/dto/BaseResponseDto.java
- com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/presentation/dto/ProductIdResponseDto.java
- com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/presentation/dto/ProductInfoRequestDto.java
- com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/presentation/dto/ProductInfoResponseDto.java
- com.trillionares.tryit.product/src/main/resources/application.yml
- com.trillionares.tryit.product/src/test/java/com/trillionares/tryit/product/ProductApplicationTests.java
- com.trillionares.tryit.product/src/test/java/com/trillionares/tryit/product/domain/service/ProductServiceTest.java
- com.trillionares.tryit.product/src/test/resources/application-test.yml
Close #15
- 상품 삭제 API 개발
카테고리 기능 반영
> [Feat/product-delete] 상품 삭제 API 개발

- com.trillionares.tryit.product/build.gradle
- com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/ProductApplication.java
- com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/domain/common/base/BaseEntity.java
- com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/domain/model/category/Category.java
- com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/domain/model/category/ProductCategory.java
- com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/domain/model/product/Product.java
- com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/domain/repository/CategoryRepository.java
- com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/domain/repository/ProductCategoryRepository.java
- com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/domain/repository/ProductRepository.java
- com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/domain/repository/ProductRepositoryCustom.java
- com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/domain/service/CategoryService.java
- com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/domain/service/ProductService.java
- com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/infrastructure/config/JpaConfig.java
- com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/infrastructure/config/QueryDslConfig.java
- com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/presentation/controller/CategoryController.java
- com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/presentation/controller/ProductController.java
- com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/presentation/dto/BaseResponseDto.java
- com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/presentation/dto/CategoryIdResponseDto.java
- com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/presentation/dto/CategoryInfoRequestDto.java
- com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/presentation/dto/ProductIdResponseDto.java
- com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/presentation/dto/ProductInfoRequestDto.java
- com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/presentation/dto/ProductInfoResponseDto.java
- com.trillionares.tryit.product/src/main/resources/application.yml
- com.trillionares.tryit.product/src/test/java/com/trillionares/tryit/product/ProductApplicationTests.java
- com.trillionares.tryit.product/src/test/java/com/trillionares/tryit/product/domain/service/ProductServiceTest.java
- com.trillionares.tryit.product/src/test/resources/application-test.yml
Close #17 
- 카테고리 등록 API 작성
- 상품 등록 시 카테고리 연결
- 상품 조회 시 카테고리 함께 조회
- 상품 카테고리 수정
- 상품 수정 시 변경 사항 확인 후 변경 내용만 수정
이미지 서버 or 참가단 신청 로직
> [Feat/category] 상품-카테고리 연결

- com.trillionares.tryit.statistics/src/main/java/com/trillionares/tryit/statistics/application/dto/request/StatisticsCreateRequestDto.java
- com.trillionares.tryit.statistics/src/main/java/com/trillionares/tryit/statistics/application/dto/response/StatisticsCreateResponseDto.java
- com.trillionares.tryit.statistics/src/main/java/com/trillionares/tryit/statistics/application/service/StatisticsService.java
- com.trillionares.tryit.statistics/src/main/java/com/trillionares/tryit/statistics/domain/common/base/BaseEntity.java
- com.trillionares.tryit.statistics/src/main/java/com/trillionares/tryit/statistics/domain/model/Statistics.java
- com.trillionares.tryit.statistics/src/main/java/com/trillionares/tryit/statistics/domain/respository/StatisticsRepository.java
- com.trillionares.tryit.statistics/src/main/java/com/trillionares/tryit/statistics/infrastructure/persistence/StatisticsRepositoryImpl.java
- com.trillionares.tryit.statistics/src/main/java/com/trillionares/tryit/statistics/presentation/controller/StatisticsController.java
- com.trillionares.tryit.statistics/src/main/java/com/trillionares/tryit/statistics/presentation/dto/BaseResponse.java
- com.trillionares.tryit.statistics/src/main/java/com/trillionares/tryit/statistics/presentation/dto/StatisticsCreateRequest.java
Close #59 
-  이전 에러 및 수정사항에 대한 내용 반영
- 공통 응답
- 유저 필드 추가
- Request, Response Dto 생성
- 통계 생성 API 구현
- 통계 생성 API 수동 테스트
- 없음
- 요청에 대한 값 검증 수행
- 테스트 코드 작성
> [Feat/statistics-create] 통계 생성 API 개발

- com.trillionares.tryit.statistics/src/main/java/com/trillionares/tryit/statistics/application/dto/request/StatisticsCreateRequestDto.java
- com.trillionares.tryit.statistics/src/main/java/com/trillionares/tryit/statistics/application/dto/response/StatisticsCreateResponseDto.java
- com.trillionares.tryit.statistics/src/main/java/com/trillionares/tryit/statistics/application/dto/response/StatisticsGetResponseDto.java
- com.trillionares.tryit.statistics/src/main/java/com/trillionares/tryit/statistics/application/service/StatisticsService.java
- com.trillionares.tryit.statistics/src/main/java/com/trillionares/tryit/statistics/domain/common/base/BaseEntity.java
- com.trillionares.tryit.statistics/src/main/java/com/trillionares/tryit/statistics/domain/model/Statistics.java
- com.trillionares.tryit.statistics/src/main/java/com/trillionares/tryit/statistics/domain/respository/StatisticsRepository.java
- com.trillionares.tryit.statistics/src/main/java/com/trillionares/tryit/statistics/infrastructure/persistence/StatisticsRepositoryImpl.java
- com.trillionares.tryit.statistics/src/main/java/com/trillionares/tryit/statistics/presentation/controller/StatisticsController.java
- com.trillionares.tryit.statistics/src/main/java/com/trillionares/tryit/statistics/presentation/dto/BaseResponse.java
- com.trillionares.tryit.statistics/src/main/java/com/trillionares/tryit/statistics/presentation/dto/StatisticsCreateRequest.java
Close #61 
- Response Dto 생성
- 통계 전체 조회 API 구현
- 통계 전체 조회 API 수동 테스트
- 없음
- 검증 수행 및 상세 기능 추가
- 테스트 코드 작성
> [Feat/statistics-read-all] 통계 전체 조회 API 개발

- com.trillionares.tryit.trial/src/main/java/com/trillionares/tryit/trial/jhtest/domain/service/TrialService.java
- com.trillionares.tryit.trial/src/main/java/com/trillionares/tryit/trial/jhtest/presentation/dto/SendNotificationDto.java
- com.trillionares.tryit.trial/src/main/java/com/trillionares/tryit/trial/jhtest/presentation/dto/common/kafka/KafkaMessage.java
…pleted submission
Close #85
- 체험단 신청시 '신청 완료'알림 kafka message 발행 안되는 버그 해
> [Feat/trial-kafka-bug] 체험단 신청시 - Kafka 비동기 통신 연동 bug fix

- com.trillionares.tryit.statistics/build.gradle
- com.trillionares.tryit.statistics/src/main/java/com/trillionares/tryit/statistics/libs/exception/ErrorCode.java
- com.trillionares.tryit.statistics/src/main/java/com/trillionares/tryit/statistics/libs/exception/ErrorResponse.java
- com.trillionares.tryit.statistics/src/main/java/com/trillionares/tryit/statistics/libs/exception/ExceptionConverter.java
- com.trillionares.tryit.statistics/src/main/java/com/trillionares/tryit/statistics/libs/exception/GlobalException.java
- com.trillionares.tryit.statistics/src/main/java/com/trillionares/tryit/statistics/libs/exception/GlobalExceptionHandler.java
- com.trillionares.tryit.statistics/src/main/java/com/trillionares/tryit/statistics/presentation/controller/StatisticsController.java
- com.trillionares.tryit.statistics/src/main/java/com/trillionares/tryit/statistics/presentation/dto/StatisticsCreateRequest.java
Close #83 
- validation 의존성 추가
- 에러 및 예외 처리 파일 생성
- 리뷰 생성
- 없음
> [Feat/statistics-validation] 통계 검증 및 예외처리

- com.trillionares.tryit.review/build.gradle
- com.trillionares.tryit.review/src/main/java/com/trillionares/tryit/review/application/service/ReviewService.java
- com.trillionares.tryit.review/src/main/java/com/trillionares/tryit/review/libs/exception/ErrorCode.java
- com.trillionares.tryit.review/src/main/java/com/trillionares/tryit/review/libs/exception/ErrorResponse.java
- com.trillionares.tryit.review/src/main/java/com/trillionares/tryit/review/libs/exception/ExceptionConverter.java
- com.trillionares.tryit.review/src/main/java/com/trillionares/tryit/review/libs/exception/GlobalException.java
- com.trillionares.tryit.review/src/main/java/com/trillionares/tryit/review/libs/exception/GlobalExceptionHandler.java
- com.trillionares.tryit.review/src/main/java/com/trillionares/tryit/review/presentation/controller/ReviewController.java
- com.trillionares.tryit.review/src/main/java/com/trillionares/tryit/review/presentation/dto/ReviewCreateRequest.java
- com.trillionares.tryit.review/src/main/java/com/trillionares/tryit/review/presentation/dto/ReviewUpdateRequest.java
Close #76 
- validation 의존성 추가
- 에러 및 예외 처리 파일 생성
- 리뷰 생성
- 리뷰 조회
- 리뷰 수정
- 리뷰 삭제
- 없음
> [Feat/review-validation] 리뷰 검증 및 예외처리

- com.trillionares.tryit.review/src/main/resources/application.yml
- com.trillionares.tryit.statistics/src/main/resources/application.yml
Close #92 
- review service 재설정
- statistics service 재설정
- statistics service 환경변수명 수정
- 없음
- 없음
> [Fix/review-statistics-setting] config server 설정 테스트

- com.trillionares.tryit.auth/src/main/resources/application.yml
Close #
- 환경변수에서 DB부분 auth 스키마의 유저와 비밀번호를 읽게끔 수정
```
username: ${DB_AUTH_USERNAME}
password: ${DB_AUTH_PASSWORD}
```
> [feat/gateway]: 환경변수에서 DB부분 auth 스키마의 유저와 비밀번호를 읽게끔 수정

- com.trillionares.tryit.auth/src/main/resources/application.yml
- com.trillionares.tryit.gateway/src/main/resources/application.yml
Close #
- 환경변수 SECRET-KEY로 변수명 수정
> [feat/gateway]: 환경변수 SECRET-KEY로 변수명 수정

- com.trillionares.tryit.trial/src/main/java/com/trillionares/tryit/trial/jhtest/domain/service/TrialService.java
- com.trillionares.tryit.trial/src/main/java/com/trillionares/tryit/trial/jhtest/presentation/dto/SendRecruitmentDto.java
Close #100 
- 체험단 모집에게 Message 전송을 위한 Producer 생성
> [Feat/trial-kafka] 체험단 모집에게 Message 전송을 위한 Producer 생성

- com.trillionares.tryit.trial/src/main/java/com/trillionares/tryit/trial/jhtest/domain/service/TrialEndpoint.java
- com.trillionares.tryit.trial/src/main/java/com/trillionares/tryit/trial/jhtest/domain/service/TrialService.java
- com.trillionares.tryit.trial/src/main/java/com/trillionares/tryit/trial/jhtest/infrastructure/messaging/kafka/ConsumerApplicationKafkaConfig.java
- com.trillionares.tryit.trial/src/main/java/com/trillionares/tryit/trial/jhtest/presentation/dto/SendNotificationDto.java
- com.trillionares.tryit.trial/src/main/java/com/trillionares/tryit/trial/jhtest/presentation/dto/UpdateStatusDto.java
Close #104 104
-  ConsumerApplicationKafkaConfig 생성
- KafkaListener EndPoint 비즈니스 로직 개발
- 체험단 모집으로부터 Message를 수신할 UpdateStatus Dto 작성
> [Feat/trial-kafka] 신청 상태 변경을 위한 consumer 생성

- com.trillionares.tryit.trial/src/main/java/com/trillionares/tryit/trial/jhtest/domain/service/TrialService.java
- com.trillionares.tryit.trial/src/main/java/com/trillionares/tryit/trial/jhtest/presentation/controller/trialController.java
…ubmit
Close #111 
- 리뷰제출시 당첨 -> 리뷰 제출 상태 업데이트 요청 endpoint
> [feat/trial-submitReview] feat: 리뷰제출시 '당첨 -> 리뷰 제출' 상태 업데이트 요청 endpoint

- com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/presentation/dto/common/kafka/KafkaMessage.java
- com.trillionares.tryit.trial/src/main/java/com/trillionares/tryit/trial/jhtest/domain/service/TrialService.java
- com.trillionares.tryit.trial/src/main/java/com/trillionares/tryit/trial/jhtest/presentation/dto/common/kafka/KafkaMessage.java
Close #114
- kafka message 포맷 변경
> [refactor/kafkamessage] refactor: kafka message 포맷 변경

- docker-compose.yml
Close #[이슈번호]
- Docker compose에 Zipkin 설정 추가
> [docs/docker-compose] docs: Docker compose에 Zipkin 설정 추가

- com.trillionares.tryit.gateway/src/main/resources/application.yml
> fix: 게이트웨이 yml의 라우팅 부분 수정

- com.trillionares.tryit.auth/src/main/java/com/trillionares/tryit/auth/infrastructure/config/jwt/JwtUtil.java
- com.trillionares.tryit.auth/src/main/java/com/trillionares/tryit/auth/presentation/controller/UserController.java
- com.trillionares.tryit.gateway/src/main/java/com/trillionares/tryit/gateway/config/GatewayConfig.java
- com.trillionares.tryit.gateway/src/main/java/com/trillionares/tryit/gateway/filter/JwtAuthFilter.java
- com.trillionares.tryit.gateway/src/main/java/com/trillionares/tryit/gateway/jwt/JwtUtil.java
- com.trillionares.tryit.gateway/src/main/resources/application.yml
Close #[이슈번호]
- 토큰 생성시 subject외에도 claim으로 추가
- 게이트웨이에 로그 추가
- 응답헤더에 나오도록 추가
- 유저서비스에 테스트용 api추가
로그가 안찍힘, 헤더가 안들어가고null로찍힘-> 토큰 생성과 추출 부분 검토+JwtAuthFilter를 글로벌필터로 config로 적용
- 포스트맨
--
- 게이트웨이 콘솔 로그
```
2025-01-15T18:24:14.411+09:00  INFO 1744 --- [gateway-service] [io-19091-exec-2] c.t.tryit.gateway.filter.JwtAuthFilter   : JwtAuthFilter 실행됨
2025-01-15T18:24:14.470+09:00  INFO 1744 --- [gateway-service] [io-19091-exec-2] c.t.tryit.gateway.jwt.JwtUtil            : 토큰에서 추출한 사용자 이름: gamja15
2025-01-15T18:24:14.473+09:00  INFO 1744 --- [gateway-service] [io-19091-exec-2] c.t.tryit.gateway.jwt.JwtUtil            : 토큰에서 추출한 역할: ROLE_MEMBER
2025-01-15T18:24:14.473+09:00  INFO 1744 --- [gateway-service] [io-19091-exec-2] c.t.tryit.gateway.filter.JwtAuthFilter   : 헤더 추가 시도 - Username: gamja15, …
```
> [Feat/gateway] fix: 헤더값 못 받아오는 문제 해결

- com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/application/service/CategoryService.java
- com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/application/service/ProductService.java
- com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/domain/client/AuthClient.java
- com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/presentation/controller/CategoryController.java
- com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/presentation/controller/ProductController.java
- com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/presentation/dto/InfoByUsernameResponseDto.java
- com.trillionares.tryit.product/src/main/java/com/trillionares/tryit/product/presentation/dto/UserResponseDto.java
Close #122
- 상품 등록 CRUD 권한 검증 로직 추가
- 카테고리 생성 권한 검증 로직 추가
- AuthClient 추가 (동기 통신)
- FeignClient를 위한 DTO 추가
> [Feat/product-authorization] 상품 등록 CRUD & 카테고리 생성 권한 검증

- com.trillionares.tryit.trial/src/main/java/com/trillionares/tryit/trial/jhtest/domain/model/type/SubmissionStatus.java
> [feat/trial-notification-status] fix: 체험단 신청 status 메시지 변경

- com.trillionares.tryit.notification/src/main/java/com/trillionares/tryit/notification/libs/client/auth/AuthServiceClient.java
- com.trillionares.tryit.notification/src/main/java/com/trillionares/tryit/notification/presentation/controller/NotificationController.java
- com.trillionares.tryit.trial/src/main/java/com/trillionares/tryit/trial/jhtest/domain/client/AuthClient.java
Close #[이슈번호]
- 체험단 신청 로직 에러 수정
> Bug: 체험단 신청 로직 에러 수정

- com.trillionares.tryit.auth/build.gradle
- com.trillionares.tryit.config/src/main/resources/config-repo/auth-service.yml
- com.trillionares.tryit.config/src/main/resources/config-repo/notification-service.yml
- com.trillionares.tryit.config/src/main/resources/config-repo/product-service.yml
- com.trillionares.tryit.config/src/main/resources/config-repo/review-service.yml
- com.trillionares.tryit.config/src/main/resources/config-repo/statistics-service.yml
- com.trillionares.tryit.config/src/main/resources/config-repo/trial-service.yml
- com.trillionares.tryit.notification/build.gradle
- com.trillionares.tryit.product/build.gradle
- com.trillionares.tryit.product/src/main/resources/application.yml
- com.trillionares.tryit.review/build.gradle
- com.trillionares.tryit.statistics/build.gradle
- com.trillionares.tryit.trial/build.gradle
- com.trillionares.tryit.trial/src/main/resources/application.yml
> feat: 전체 서비스 config server 에 zipkin 설정 추가

- .github/workflows/aws.yml
> :memo: docs: Create aws.yml - trial-service

- .github/workflows/trial-task-revision1.json
> :memo: add: revision file

- com.trillionares.tryit.auth/Dockerfile
- com.trillionares.tryit.config/Dockerfile
- com.trillionares.tryit.gateway/Dockerfile
- com.trillionares.tryit.image-manage/Dockerfile
- com.trillionares.tryit.notification/Dockerfile
- com.trillionares.tryit.product/Dockerfile
- com.trillionares.tryit.review/Dockerfile
- com.trillionares.tryit.server/Dockerfile
- com.trillionares.tryit.statistics/Dockerfile
- com.trillionares.tryit.trial/Dockerfile
Close #[이슈번호]
- 각 서비스 Dockerfile 추가
> :memo: docs: add dockerfile

- .github/workflows/server-task-revision1.json
> :rotating_light: fix: Update server-task-revision1.json

- .github/workflows/aws.yml
> :rotating_light: fix: Update aws.yml

- .github/workflows/aws.yml
> :rotating_light: fis: Update aws.yml

- com.trillionares.tryit.config/src/main/resources/config-repo/notification-service.yml
- com.trillionares.tryit.notification/build.gradle
- com.trillionares.tryit.notification/src/main/resources/application.yml
- prometheus 의존성 추가
Close #57 
- notification server 환경 변수 반영
- 환경 변수 사용하는 항목들 대상으로 전체 서비스에 적용하려고 합니다 ! 확인해주시고 의견 부탁드립니다!
> refactor : config 서버 환경변수 반영

- com.trillionares.tryit.auth/src/main/resources/application.yml
- com.trillionares.tryit.config/src/main/resources/application.yml
- com.trillionares.tryit.config/src/main/resources/config-repo/image-manage-service.yml
- com.trillionares.tryit.gateway/src/main/resources/application.yml
- com.trillionares.tryit.image-manage/src/main/resources/application.yml
- com.trillionares.tryit.notification/src/main/resources/application.yml
- com.trillionares.tryit.product/src/main/resources/application.yml
- com.trillionares.tryit.review/src/main/resources/application.yml
- com.trillionares.tryit.statistics/src/main/resources/application.yml
- com.trillionares.tryit.trial/src/main/resources/application.yml
> [Deploy/setting] 배포를 위한 DNS 세팅

- .github/workflows/aws.yml
- com.trillionares.tryit.auth/src/main/resources/application.yml
- com.trillionares.tryit.product/src/main/resources/application.yml
- com.trillionares.tryit.review/src/main/resources/application.yml
- com.trillionares.tryit.statistics/src/main/resources/application.yml
> [Deploy/setting] deploy: 배포

- .github/workflows/aws.yml
- com.trillionares.tryit.gateway/src/main/java/com/trillionares/tryit/gateway/config/GatewayCorsConfig.java
- com.trillionares.tryit.gateway/src/main/resources/application.yml
> [develop] Deploy 설정

- com.trillionares.tryit.auth/src/main/resources/application.yml
- com.trillionares.tryit.config/src/main/resources/application.yml
- com.trillionares.tryit.gateway/src/main/resources/application.yml
- com.trillionares.tryit.image-manage/src/main/resources/application.yml
- com.trillionares.tryit.notification/src/main/resources/application.yml
- com.trillionares.tryit.product/src/main/resources/application.yml
- com.trillionares.tryit.review/src/main/resources/application.yml
- com.trillionares.tryit.statistics/src/main/resources/application.yml
- com.trillionares.tryit.trial/src/main/resources/application.yml
> :recycle: docs: Register DNS when registering service in eureka

- .github/workflows/aws.yml
- com.trillionares.tryit.trial/src/main/java/com/trillionares/tryit/trial/jhtest/domain/service/TrialService.java
> :recycle: docs: deploy branch

- com.trillionares.tryit.auth/build.gradle
- com.trillionares.tryit.auth/src/main/java/com/trillionares/tryit/auth/application/dto/InfoByUsernameResponseDto.java
- com.trillionares.tryit.auth/src/main/java/com/trillionares/tryit/auth/application/service/UserService.java
- com.trillionares.tryit.auth/src/main/java/com/trillionares/tryit/auth/infrastructure/config/CacheConfig.java
- com.trillionares.tryit.auth/src/main/java/com/trillionares/tryit/auth/infrastructure/config/RedisConfig.java
- com.trillionares.tryit.auth/src/main/java/com/trillionares/tryit/auth/infrastructure/config/SecurityConfig.java
- com.trillionares.tryit.auth/src/main/java/com/trillionares/tryit/auth/presentation/controller/UserController.java
- com.trillionares.tryit.auth/src/main/java/com/trillionares/tryit/auth/presentation/dto/responseDto/UserResponseDto.java
- com.trillionares.tryit.auth/src/main/resources/application.yml
- com.trillionares.tryit.gateway/src/main/java/com/trillionares/tryit/gateway/filter/JwtAuthFilter.java
Close #200 
- 레디스 설정 추가
- 서비스에 캐싱 적용
> [feat/user-redis] feat: 사용자 조회부분 레디스 적용
